### PR TITLE
Add GeometricFlux GCN model

### PR DESCRIPTION
**Pull request by yuehhua**
Resolves FluxML/GeometricFlux.jl#228

### CODE REVIEW

**Comment by yuehhua** [comment]
@DhairyaLGandhi 
It seems that some model in Metalhead out of memory.

```
(5/7) benchmarking "Metalhead"...
--
  | (1/24) benchmarking "Backwards_Pass_Metalhead.ResNet_18_with_batchsize_5"...
  | done (took 49.529997481 seconds)
  | (2/24) benchmarking "Backwards_Pass_Metalhead.GoogLeNet_nothing_with_batchsize_5"...
  | done (took 1107.592323536 seconds)
  | (3/24) benchmarking "Backwards_Pass_Metalhead.ResNet_34_with_batchsize_10"...
  | done (took 94.619881626 seconds)
  | (4/24) benchmarking "Forward_Pass_Metalhead.ResNet_34_with_batchsize_10"...
  | done (took 3.67873324 seconds)
  | (5/24) benchmarking "Backwards_Pass_Metalhead.ResNet_50_with_batchsize_10"...
  | NVML.compute_processes(d) = Dict{Int64, NamedTuple{(:used_gpu_memory,), Tuple{Int64}}}(29645 => (used_gpu_memory = 6405750784,))
  | ERROR: Out of GPU memory trying to allocate 724.556 MiB
  | Effective GPU memory usage: 76.58% (5.970 GiB/7.795 GiB)
  | Memory pool usage: 3.033 GiB (5.250 GiB reserved)
```

**Comment by DhairyaLGandhi** [comment]
can you try to merge the main branch into this?

**Comment by DhairyaLGandhi** [comment]
```Julia
ERROR: LoadError: InitError: could not load library "/root/.cache/julia-buildkite-plugin/depots/df646e51-ac52-453c-b19b-c355be13a749/conda/3/lib/libpython3.9.so.1.0"
--
  | /root/.cache/julia-buildkite-plugin/depots/df646e51-ac52-453c-b19b-c355be13a749/conda/3/lib/libpython3.9.so.1.0: cannot open shared object file: No such file or directory

```

**Comment by yuehhua** [comment]
Since it doesn't have a test case, is there a way to run whole process? Then, I can check it locally.

**Comment by yuehhua** [comment]
I ran it locally, and it seems fine.
```julia
julia> FluxBench.bench()
  Downloaded artifact: yolov3-COCO
[ Info: Precompiling PNGFiles [f57f5aa1-a3ce-4bc8-8ab9-96f992907883]
  Downloaded artifact: yolov3-tiny-COCO
Total: 441026658 bytes
Downloaded: 441026658 bytes (100%)
[ Info: loading pretrain bert model: uncased_L-12_H-768_A-12.tfbson bert_model
┌ Warning: use values(kwargs) and keys(kwargs) instead of kwargs.data and kwargs.itr
│   caller = #CompositeEmbedding#27 at etype.jl:20 [inlined]
└ @ Core ~/.julia/packages/Transformers/05NZz/src/basic/embeds/etype.jl:20
┌ Warning: use values(kwargs) and keys(kwargs) instead of kwargs.data and kwargs.itr
│   caller = #_create_classifier#27 at tfckpt2bson.jl:137 [inlined]
└ @ Core ~/.julia/packages/Transformers/05NZz/src/bert/tfckpt2bson.jl:137
```

**Comment by DhairyaLGandhi** [comment]
You'll also need to do `run(SUITE, verbose = true)`

**Comment by yuehhua** [comment]
```julia
julia> run(FluxBench.SUITE, verbose = true)
(1/7) benchmarking "ObjectDetector"...
  (1/4) benchmarking "ObjectDetector_v3_608_COCO_with_batchsize_3"...
  done (took 77.194462905 seconds)
  (2/4) benchmarking "ObjectDetector_v3_tiny_416_COCO_with_batchsize_1"...
  done (took 9.832644238 seconds)
  (3/4) benchmarking "ObjectDetector_v3_tiny_416_COCO_with_batchsize_3"...
  done (took 7.505900821 seconds)
  (4/4) benchmarking "ObjectDetector_v3_608_COCO_with_batchsize_1"...
  done (took 10.98774473 seconds)
done (took 108.288713662 seconds)
(2/7) benchmarking "Flux3D"...
  (1/5) benchmarking "Flux3D_TriMesh_Conversion"...
  done (took 22.93557797 seconds)
  (2/5) benchmarking "Flux3D_VoxelGrid_Conversion"...
  done (took 14.601358091 seconds)
  (3/5) benchmarking "Flux3D_TriMesh_Forward_Pass"...
  done (took 19.353135954 seconds)
  (4/5) benchmarking "Flux3D_TriMesh_Backward_Pass"...
  done (took 130.395692347 seconds)
  (5/5) benchmarking "Flux3D_PointCloud_Conversion"...
  done (took 8.563843906 seconds)
...
(7/7) benchmarking "GeometricFlux"...
  (1/8) benchmarking "GeometricFlux_GCN_Forward_hidden_16_bch_sz_16"...
  done (took 47.625141169 seconds)
  (2/8) benchmarking "GeometricFlux_GCN_Backward_hidden_16_bch_sz_16"...
  done (took 18.127732228 seconds)
  (3/8) benchmarking "GeometricFlux_GCN_Forward_hidden_32_bch_sz_8"...
  done (took 13.592055625 seconds)
  (4/8) benchmarking "GeometricFlux_GCN_Forward_hidden_16_bch_sz_8"...
  done (took 13.539599591 seconds)
  (5/8) benchmarking "GeometricFlux_GCN_Backward_hidden_32_bch_sz_16"...
  done (took 13.784720423 seconds)
  (6/8) benchmarking "GeometricFlux_GCN_Backward_hidden_16_bch_sz_8"...
  done (took 13.578782695 seconds)
  (7/8) benchmarking "GeometricFlux_GCN_Backward_hidden_32_bch_sz_8"...
  done (took 14.18690879 seconds)
  (8/8) benchmarking "GeometricFlux_GCN_Forward_hidden_32_bch_sz_16"...
  done (took 12.936008084 seconds)
done (took 154.682591754 seconds)
```

**Comment by yuehhua** [comment]
OK, it works. It lacks of setting PyCall environment.

**Comment by DhairyaLGandhi** [comment]
LGTM, merging for now!

**Comment by yuehhua** [comment]
Well, may I just use the dataset from GraphMLDatasets.jl, which needs PyCall.jl.

**Pull request merged**
